services:
  - type: web
    name: read-rank-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://accounts-api.empowered.vote
      - key: NPM_TOKEN
        sync: false
